const salaryBatchesTable = `
  CREATE TABLE intect.salary_batches (
    "Id" INTEGER PRIMARY KEY,
    "SalaryBatchNumber" INTEGER,
    "CompanyId" BIGINT,
    "SalaryPeriodId" BIGINT,
    "Created" TIMESTAMP,
    "StatusId" INTEGER,
    "Approved" TIMESTAMP NULL,
    "RejectionReason" TEXT,
    "Rejected" TIMESTAMP NULL,
    "EIncomeTransferDate" TIMESTAMP NULL,
    "Message" TEXT,
    "PayoutDate" TIMESTAMP,
    "ApprovedUserId" BIGINT NULL,
    "RejectedUserId" BIGINT NULL,
    "CreatedUserId" BIGINT NULL,
    "HasErrors" BOOLEAN,
    "HasWarnings" BOOLEAN,
    "ValidationStatusCode" TEXT,
    "NetsPaymentsProcessingDate" TIMESTAMP NULL,
    "IsTermination" BOOLEAN,
    "EIncomeZeroReport" BOOLEAN,
    "PaymentMethodSalary" INTEGER,
    "PaymentMethodTax" INTEGER,
    "PaymentMethodPension" INTEGER,
    "EIncomeReruns" INTEGER,
    "PayslipsArchived" BOOLEAN,
    "LimitToSpecificEmployees" BOOLEAN,
    "CreatedByUserFullName" TEXT,
    "ApprovedByUserFullName" TEXT,
    "RejectedByUserFullName" TEXT,
    "FinalizedByUserFullName" TEXT,
    "PeriodStartDate" TIMESTAMP,
    "PeriodEndDate" TIMESTAMP,
    "SalaryCycleId" INTEGER,
    "StatusName" TEXT,
    "LanguageId" BIGINT,
    "PayoutAllFlex" BOOLEAN,
    "PayoutNewFlex" BOOLEAN,
    "Description" TEXT,
    "IsImport" BOOLEAN,
    "PaymentMethodPublicPension" INTEGER,
    "PaymentMethodVacationProvider" INTEGER,
    "AllowPreliminaryPayslips" BOOLEAN,
    "EBoksDeliveryEnabled" BOOLEAN,
    "HasNemKontoPayments" BOOLEAN,
    "IsAutomated" BOOLEAN,
    "Finalized" TIMESTAMP NULL,
    "ToArchive" BOOLEAN,
    "FromDateOverride" TIMESTAMP NULL,
    "ToDateOverride" TIMESTAMP NULL,
    "SpecifiedEmployees" TEXT NULL,
    "PaymentMethodMaternityProgram" INTEGER,
    "AutoFinalize" BOOLEAN,
    "DispatchDate" TIMESTAMP,
    "ToDispatch" BOOLEAN,
    "TypeId" INTEGER,
    "ExportFeedbackStatusId" INTEGER NULL
  );
`;

const intectSchema = {
  salaryBatchesTable,
};

export default intectSchema;
