export const PROJECTS_HEADERS = [
  "id",
  "company_project_id",
  "custom_project_id",
  "name",
  "connected_project",
  "stage",
  "status",
  "status_description",
  "description",
  "priority_level_id",
  "color",
  "estimation_units",
  "minutes_per_estimation_point",
  "budget",
  "billable",
  "budget_type",
  "use_sprints",
  "sprint_length",
  "start_date",
  "end_date",
  "use_task_owner",
  "use_task_followers",
  "use_sub_tasks",
  "client",
  "rate_card",
  "remaining_auto_calculated",
  "use_project_allocations",
  "use_baseline",
  "baseline_win_chance",
  "baseline_target",
  "labels",
  "external_refs",
  "progress",
  "default_period_periodicity",
  "default_period_length",
  "default_period_budget_type",
  "default_period_hours_amount",
  "default_period_price_amount",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const PERSON_COST_PERIODS_HEADERS = [
  "id",
  "person_id",
  "start_year",
  "start_month",
  "start_day",
  "cost",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const EXPENSE_ITEMS_HEADERS = [
  "id",
  "project_id",
  "name",
  "expense_date",
  "cost",
  "price",
  "quantity",
  "approved",
  "billable",
  "notes",
  "person_id",
  "expense_category",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
  "phase_id",
  "part_of_fixed_price",
] as const;

export const EXPENSE_CATEGORIES_HEADERS = [
  "id",
  "name",
  "disabled",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const PERSONS_HEADERS = [
  "id",
  "first_name",
  "last_name",
  "email",
  "job_title",
  "client_id",
  "holiday_calendar_id",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "active",
  "default_role",
  "department_id",
  "cost",
  "language",
  "start_date",
  "end_date",
  "permissions",
  "is_system_user",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const RATE_CARDS_HEADERS = [
  "id",
  "name",
  "default_rate",
  "currency",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const TIME_REGISTRATIONS_HEADERS = [
  "id",
  "person",
  "project",
  "role",
  "billable_minutes_registered",
  "phase",
  "task",
  "task_project",
  "non_project_time",
  "is_internal_time",
  "time_registered",
  "date",
  "notes",
  "approval_status",
  "invoice_entry",
  "invoice",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const NON_PROJECT_TIME_HEADERS = [
  "id",
  "name",
  "is_internal_time",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const ALLOCATIONS_HEADERS = [
  "id",
  "project",
  "connected_project",
  "non_project_time",
  "person",
  "start_date",
  "end_date",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "notes",
  "is_soft",
  "created_by",
  "updated_by",
  "created_at",
  "updated_at",
] as const;

export const FORECAST_HEADERS = {
  projects: PROJECTS_HEADERS,
  person_cost_periods: PERSON_COST_PERIODS_HEADERS,
  expense_items: EXPENSE_ITEMS_HEADERS,
  expense_categories: EXPENSE_CATEGORIES_HEADERS,
  persons: PERSONS_HEADERS,
  rate_cards: RATE_CARDS_HEADERS,
  time_registrations: TIME_REGISTRATIONS_HEADERS,
  non_project_time: NON_PROJECT_TIME_HEADERS,
  allocations: ALLOCATIONS_HEADERS,
} as const;
